version: '3'
services:

############## Greenplum 6 master node ################### 
  greenplum: # gpadmin/123456  DB: postgres
    image: "andruche/greenplum:6.24.1"
    # build: 
    #   context: .
    #   dockerfile: ./6/DockerFile
    ports:
      - 5432:5432  
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/gpdb/bin/psql -h greenplum -U gpadmin -d postgres -c \"SELECT 2+2;\" | grep 4"]
      start_period: 5s
      interval: 5s
      timeout: 60s
      retries: 20      

    environment: 
     - LANG=en_US.UTF-8 
     - LANGUAGE=en_US:en 
     - LC_ALL=en_US.UTF-8     
    networks:
      - internal

######### WEB dbeaver #######
### https://github.com/dbeaver/cloudbeaver/wiki/Run-Docker-Container
  cloudbeaver:
    image: "dbeaver/cloudbeaver:latest"
    restart: unless-stopped
    ports:
      - "8978:8978"
    networks:
      - internal

networks:
  internal: